name: Tests
on: push
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: 3.8.6
        architecture: x64
    - run: pip install nox==2020.8.22
    - run: pip install poetry==1.1.4
    - run: nox
